### ISSUE TITLE
关于小程序的后台

### ISSUE THREAD

**Issue by 1379** [choyri/WeGifun#2]
你好，这简直是一个太棒的小程序了！想给我们学校也整一个，请问你这个有后台吗，还是说自己要从头适配一个后台出来呀？

**Comment by choyri** [comment]
服务端因为和学校业务有点耦合，目前不方便开源噢。
你可以用喜欢和擅长的语言自己实现~ 😄

**Comment by 1379** [comment]
那有接口文档吗？还有一个问题想问一下，你是通过类似爬虫的方式实现充电费还有课程表之类的功能的吗，或者是学校给了相应的接口啊

**Comment by choyri** [comment]
没有文档诶…… 😅
实现方式是模拟登录，即你所提到的爬虫。
